# Vagrant
alias v='vagrant $*'
alias vd='vagrant destroy --force'
alias vgs='vagrant global-status'
alias vgsp='vagrant global-status --prune'
alias vh='vagrant halt'
alias vssh='vagrant ssh'
alias vsshc='vagrant ssh-config'
alias vu='vagrant up'
alias vbox='vagrant box'
alias vsus='vagrant suspend'
alias vres='vagrant resume'
alias vstat='vagrant status'
alias vsnap='vagrant snapshot'
alias vrel='vagrant reload'
alias vp='vagrant provision'
